### ISSUE TITLE
unclear docs for `render`?

### ISSUE THREAD

**Issue by jsta** [odeleongt/postr#6]
I was confused when trying out the package that the initial call to `render` (on the Rmd) produces a png that is **NOT** the final product. I deduced from the examples that `render` needs to be run once on the Rmd **and** a second time on the html to produce the final product. Should the docs for render explicitly say that the function should be run twice?

**Comment by odeleongt** [comment]
Thanks for the input. If you are getting two different pngs from this process (i.e. one when running `knitr::render` on an Rmd with `render_print` set to `TRUE` and another when running `postr::render` on the final html), please provide a reproducible example so I can look into it, since I have not yet found a case when this happens. There are two "render" functions relevant to this:

With `knitr::render` run on an `Rmd` document using the `postr::flex_dashboard_poster` template (or using the Knit button in RStudio), you will by default get an html. As stated in `?postr::flex_dashboard_poster`, the png image will be rendered if the option `render_print: true` is defined in the YAML header; this is triggered when exiting the html rendering by `knitr`, so it should always work on the final html that you get.

On the other hand `postr::render` will only work on an html (it basically just instructs `webshot::webshot` to save the html to a png using some defaults for size and resolution, which can be changed in the YAML header or the call to the function).

That said, I agree that the documentation needs more work and will come to it eventually. If you believe this could be explained better in the docs feel free to submit a pull request and I'll be happy to include your contributions.

**Comment by odeleongt** [comment]
If you are not changing the html output from knitr, and you get different pngs, the main source of the difference could be the `delay` parameter which instructs `PhantomJS` to wait `delay` seconds to let the html render. For very complex htmls, slow computers or slow connections (when web content is loaded) this time could need to be set to a larger number.

**Comment by jsta** [comment]
Hmm, it seems to work fine the first time when run on a minimal example. I suspect the `delay` parameter is to blame as you say.
